name: Update website

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        working-directory: './generator'
    - run: |
        cd generator
        bundle exec ruby run.rb > ../index.html
    - name: Commit website
      run: |
        git config --global user.name 'Piotr Heilman'
        git config --global user.email 'piohei@users.noreply.github.com'
        git add index.html
        git commit -m "Updated website"
        git push